spring.application.name=kotto-backend

server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/kotto?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=kotto_user
spring.datasource.password=StrongPass123!

spring.jpa.hibernate.ddl-auto=update

# JWT (must be 32+ chars)
app.jwt.secret=KOTTO_SUPER_SECRET_KEY_1234567890_ABCDEF!!
app.jwt.expiration-ms=86400000

# Frontend URL for reset password link
app.frontend.url=http://localhost:5173

# Email Configuration (Gmail SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=yasiru017@gmail.com
spring.mail.password=xveu xhgl uxqm gklr
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

logging.level.org.springframework.security=DEBUG
logging.level.com.kotto.be=DEBUG

# File uploads (images stored under project working directory)
app.upload.dir=uploads
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=6MB